/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uit.tool.app;

// import uit.tool.list.LinkedList;

// import static uit.tool.utilities.StringUtils.join;
// import static uit.tool.utilities.StringUtils.split;
// import static uit.tool.app.MessageUtils.getMessage;

// import org.apache.commons.text.WordUtils;

// public class App {
//     public static void main(String[] args) {
//         LinkedList tokens;
//         tokens = split(getMessage());
//         String result = join(tokens);
//         System.out.println(WordUtils.capitalize(result));
//     }
// }

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage stage) {
        String javaVersion = System.getProperty("java.version");
        String javafxVersion = System.getProperty("javafx.version");
        Label l = new Label("Hello, JavaFX " + javafxVersion + ", running on Java " + javaVersion + ".");
        Scene scene = new Scene(new StackPane(l), 640, 480);
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }

}
